version: "3.8"
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "80:80"
    networks:
      - appnet
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "86:80"
    environment:
      - DB_HOST=database-1.ckn4c840kn2f.us-east-1.rds.amazonaws.com
      - DB_USERNAME=admin
      - DB_PASSWORD=Sonal45815
      - PORT=3306
    networks:
      - appnet
   

#   mysql:
#     build:
#       context: ./mysql
#       dockerfile: Dockerfile
#     container_name: mysql-db
#     environment:
#       - MYSQL_ROOT_PASSWORD=Cloud122
#       - MYSQL_DATABASE=test
#       - MYSQL_USER=admin
#       - MYSQL_PASSWORD=Devops123
#     ports:
#       - "3306:3306"
#     networks:
#       - appnet
#     # volumes:
#     # - ./mysql_data:/var/lib/mysql

networks:
  appnet:
    driver: bridge

