apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: ZGF0YWJhc2UtMS5ja240Yzg0MGtuMmYudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
  db_username: YWRtaW4=
  db_password: U29uYWw0NTgxNQ==
