apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: sonal45815/backend-app:latest
        ports:
        - containerPort: 80   
        env:
        - name: DB_HOST
          value: "kube.cy7uw4uu0e0x.us-east-1.rds.amazonaws.com"
        - name: DB_PORT
          value: "3306"
